INSERT INTO CUSTOMER(CUSTOMER_ID, EMAIL, FIRST_NAME, LAST_NAME) VALUES(1, 'sathiya@gmail.com','sathiya', 'deva')
INSERT INTO CUSTOMER(CUSTOMER_ID, EMAIL, FIRST_NAME, LAST_NAME) VALUES(2, 'deva@gmail.com','deva', 'sathiya')

INSERT INTO PIZZA(PIZZA_ID, NAME, PRICE) VALUES(1, 'Cheese Pizza', 10.00)

INSERT INTO TOPPING(TOPPING_ID, PRICE) VALUES('Onion', 1.00)
INSERT INTO TOPPING(TOPPING_ID, PRICE) VALUES('Tomatoes', 1.00)
INSERT INTO TOPPING(TOPPING_ID, PRICE) VALUES('Mushroom', 1.00)
INSERT INTO TOPPING(TOPPING_ID, PRICE) VALUES('Chicken', 1.25)
INSERT INTO TOPPING(TOPPING_ID, PRICE) VALUES('Pepperoni', 1.25)
INSERT INTO TOPPING(TOPPING_ID, PRICE) VALUES('Ricotta', 1.50)



