INSERT INTO CUSTOMER(CUSTOMER_ID, EMAIL, FIRST_NAME, LAST_NAME) VALUES(1, 'sathiya@gmail.com','sathiya', 'deva')
INSERT INTO CUSTOMER(CUSTOMER_ID, EMAIL, FIRST_NAME, LAST_NAME) VALUES(2, 'deva@gmail.com','deva', 'sathiya')

INSERT INTO PIZZA(PIZZA_ID, NAME, PRICE) VALUES(1, 'Cheese Pizza', 10.00)

INSERT INTO TOPPING(TOPPING_ID, PRICE, AVAILABLE_QUANTITY, version) VALUES('Onion', 1.00,10,0)
INSERT INTO TOPPING(TOPPING_ID, PRICE, AVAILABLE_QUANTITY,version) VALUES('Tomatoes', 1.00, 10,0)
INSERT INTO TOPPING(TOPPING_ID, PRICE, AVAILABLE_QUANTITY, version) VALUES('Mushroom', 1.00,10,0)
INSERT INTO TOPPING(TOPPING_ID, PRICE, AVAILABLE_QUANTITY, version) VALUES('Chicken', 1.25,10,0)
INSERT INTO TOPPING(TOPPING_ID, PRICE, AVAILABLE_QUANTITY, version) VALUES('Pepperoni', 1.25,10,0)
INSERT INTO TOPPING(TOPPING_ID, PRICE, AVAILABLE_QUANTITY, version) VALUES('Ricotta', 1.50,10,0)



